apiVersion: 1

datasources:
  - name: The Pool Public Prometheus
    uid: the-pool-public-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
